### ISSUE TITLE
Apply book reader to .log format

### ISSUE THREAD

**Issue by fennectech** [joel16/NX-Shell#10]
I suggest applying the book reader to .log files as well.

**Comment by joel16** [comment]
.log file isn't associated with ebooks lol. I'd have to add that to the text reader/viewer.

**Comment by DraconicNEO** [comment]
> .log file isn't associated with ebooks lol. I'd have to add that to the text reader/viewer.

Wouldn't it be better to have a combined hex and Text viewer for log files? I know many times log files are hex dumps along with text.
