### ISSUE TITLE
Full Crash when selecting items [Y button] on an empty folder [outdated ofw/cfw]

### ISSUE THREAD

**Issue by Marin37** [joel16/NX-Shell#100]
While browsing an empty folder with the _"No file entries"_ message, if for any reason i tap the **Y button** (select items w/checkbox but there's nothing to select) the whole system crashes and Reboot to Payload is needed. 

Keep in mind, I'm using 11.0.1 Switch ofw and Atmosphere 0.18.1 cfw - **Outdated**
Last week updates for both were released, so I'll try those asap, still I'm adding this issue in the case that updating is not a solution.

![2021071418080800-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/57327931/125698983-4ff96536-52f8-4266-be07-f60821427799.jpg)

![image](https://user-images.githubusercontent.com/57327931/125699047-afee3819-8c81-4f57-9d2d-ac6003ab8d35.png)

**Comment by joel16** [comment]
Was fixed with https://github.com/joel16/NX-Shell/pull/102
