### ISSUE TITLE
Crashing on AMS 13.1.0

### ISSUE THREAD

**Issue by mistervampi** [joel16/NX-Shell#104]
Just to inform that the app is crashing on Atmosphere 1.2.1 / FW:13.1.0. I leave crash log that could be useful for debug
![IMG-20211028-233825](https://user-images.githubusercontent.com/43819059/139376783-fa032700-0c9a-47d7-adb6-ec4668807c71.jpg)
0

**Comment by joel16** [comment]
I'm reworking a few things and probably won't be available for a while.

**Comment by mistervampi** [comment]
Don't worry. Take your time ;)

**Comment by ThisNekoGuy** [comment]
I got a crash too but it was after I tried to keep copying or move stuff because neither wouldn't work :v

**Comment by joel16** [comment]
Should no longer be an issue with v4.00.
