### ISSUE TITLE
add the ability to switch archive bit on/off in exFAT.

### ISSUE THREAD

**Issue by plaidman** [joel16/NX-Shell#11]
We have this option in Hekate, but it might be useful when you already have the system booted.

**Comment by joel16** [comment]
Can you test this?
https://github.com/joel16/NX-Shell/blob/gh-pages/NX-Shell.nro

Open options (touch top right button with 3 dots or press X)
Then select More... And then set archive bit. It should set the current selected folder.

**Comment by cristianmiranda** [comment]
@plaidman you need to enable "Developer mode" in settings first.
