### ISSUE TITLE
Displayed check box and folder icon on screen only.

### ISSUE THREAD

**Issue by DDinghoya** [joel16/NX-Shell#117]
This was the first time it was launched after Korean language support.

As above title, I can see check box and folder icon only on screen. The reason why Korean character can not be printed is probably because Korean font is not supported. Is it right?

config.json's value is "multi_lang": 1

Please see the attached file.

![nx-shell](https://user-images.githubusercontent.com/19677686/183443334-1459cdb6-c58e-464b-ac6f-cc7d62128569.jpg)

**Comment by joel16** [comment]
Assuming you are using applet mode, this currently will not work in applet mode.

**Comment by DDinghoya** [comment]
> Assuming you are using applet mode, this currently will not work in applet mode.

Okay I'll check it! :)

**Comment by DDinghoya** [comment]
> Assuming you are using applet mode, this currently will not work in applet mode.

As per your advice, the same phenomenon occurred in applet mode, and characters are displayed properly when applet mode is turned off.

The output is in English, can I change it to Korean in the menu or set it manually? Any good solutions?

**Comment by joel16** [comment]
I haven't enabled a way to use language options officially, but if you *really* want to manually set it, you can edit the config.cfg file in /switch/NX-Shell and change language from 1 to 7. Make sure multi_lang is also 1. 

And as stated earlier this will only work if you run it via game. Applet doesn't have enough memory.

**Comment by fennectech** [comment]
This is applet mode.  It might be wise to add a box in a hot fix that checks the available ram and pops a message if there isnt enough

**Comment by DDinghoya** [comment]
> I haven't enabled a way to use language options officially, but if you _really_ want to manually set it, you can edit the config.cfg file in /switch/NX-Shell and change language from 1 to 7. Make sure multi_lang is also 1.
> 
> And as stated earlier this will only work if you run it via game. Applet doesn't have enough memory.

Thank you for strong your reply.

As above my comment, Based on your advice, I tested it in non-applet mode. 

I don't know what the Korean number is, Again, let's manually assign numbers 1 through 7. :)

**Comment by joel16** [comment]
> > I haven't enabled a way to use language options officially, but if you _really_ want to manually set it, you can edit the config.cfg file in /switch/NX-Shell and change language from 1 to 7. Make sure multi_lang is also 1.
> > And as stated earlier this will only work if you run it via game. Applet doesn't have enough memory.
> 
> Thank you for strong your reply.
> 
> As above my comment, Based on your advice, I tested it in non-applet mode.
> 
> I don't know what the Korean number is, Again, let's manually assign numbers 1 through 7. :)

Maybe you misunderstood, I was saying number 7 is Korean. So remove the 1 for language and use 7.

**Comment by DDinghoya** [comment]
> > > I haven't enabled a way to use language options officially, but if you _really_ want to manually set it, you can edit the config.cfg file in /switch/NX-Shell and change language from 1 to 7. Make sure multi_lang is also 1.
> > > And as stated earlier this will only work if you run it via game. Applet doesn't have enough memory.
> > 
> > 
> > Thank you for strong your reply.
> > As above my comment, Based on your advice, I tested it in non-applet mode.
> > I don't know what the Korean number is, Again, let's manually assign numbers 1 through 7. :)
> 
> Maybe you misunderstood, I was saying number 7 is Korean. So remove the 1 for language and use 7.

Korean language settings have been completed with your kind explanation. :)
