### ISSUE TITLE
(Suggestion) Port to Linux/Steam Deck?

### ISSUE THREAD

**Issue by Star-X555** [joel16/NX-Shell#122]
I know that Linux has file managers already, but what it lacks is a file manager that works with gamepads.

Is there any chance of NX-Shell/3dshell/whatever being tweaked to be able to be compiled for Linux/SteamOS instead of Switch/3ds?  It'd be amazing for Steam Deck users, as they'd be able to make filesystem tweaks without switching to desktop mode.

**Comment by joel16** [comment]
I'm not sure how the steam deck (or steam OS) works so i can't really help with that. Linux port would be do-able but given my current time, I probably won't have the bandwidth. This project still has a lot to mature before it starts hitting multiplatform in my opinion, but a Linux port may help ease testing. On the other hand it is open source so anyone can pick it up if required.

**Comment by fennectech** [comment]
steamOS is just linux
