### ISSUE TITLE
[Feature Request] Add a portrait rotation ability to the eBook reader

### ISSUE THREAD

**Issue by SuperOkazaki** [joel16/NX-Shell#14]
Currently, when opening a .pdf file or .epub, the media is displayed in portrait rotation, regardless of the content. Would it be feasible to add an option to rotate the media to the correct orientation, while also changing the navigation buttons to match?

**Comment by joel16** [comment]
Portrait rotation has been added, I just haven't released an update as yet.

**Comment by SuperOkazaki** [comment]
Thank you. Is that included in the newest source code? I compiled it myself and don't see the option.

**Comment by joel16** [comment]
Oh, didn't read properly. I don't think media rotation has been added. Perhaps @rock88 may look into it if he wises. He's the one maintaining the PDF module.

**Comment by SuperOkazaki** [comment]
I see, thank you anyway for replying and informing me. I guess I'll just have to cross my fingers and hope that gets added! If I can use my Switch as an eBook reader with this app, I will be ecstatic.

**Comment by rock88** [comment]
Portrait orientation enabled by press Y button (if you build from last master).

**Comment by SuperOkazaki** [comment]
Oh, that's awesome! Is there any possibility of having orientation-appropriate touch controls? I'm sorry if I'm asking for a lot, I just wanna be able to have a perfect eBook reader :) thanks for the work so far!

**Comment by Schneitizel** [comment]
Hi ! Thanks for you work !

I can't compile because I'm a dumb for that... Someone can send me a link for a .nro of this homebrew please? I would like read my manga scans in vertical mode (The last release doesn't use the Y button for that)

Thanks :)

(Sorry if my english is bad :/)

**Comment by joel16** [comment]
https://github.com/joel16/NX-Shell/tree/gh-pages?files=1

**Comment by Schneitizel** [comment]
Thanks very much ! **
