### ISSUE TITLE
Image viewer doesn't downscale images for viewing...

### ISSUE THREAD

**Issue by Luro02** [joel16/NX-Shell#15]
it's hard to explain with words so [here](https://i.imgur.com/3tZbjoP.jpg) is a picture. [This](https://i.imgur.com/LQ8es1y.png) is the original bmp file.

**Comment by joel16** [comment]
That is currently being worked on. https://github.com/joel16/NX-Shell/commit/6541ceae50ed6b153fbcd718cbcd9bc9de961fc3

**Comment by joel16** [comment]
Closing this as it's already been implemented.
