### ISSUE TITLE
Impossible to compile on linux because of mupdf

### ISSUE THREAD

**Issue by potjesoep** [joel16/NX-Shell#17]
```
# make
make[1]: Entering directory '/media/ExtraDocuments/SwitchHacks/NX-Shell/mupdf'
    LINK build/release/scripts/hexdump.exe
    GEN generated/resources/fonts/urw/Dingbats.cff.c
/bin/sh: build/release/scripts/hexdump.exe: cannot execute binary file: Exec format error
make[1]: *** [Makefile:144: generated/resources/fonts/urw/Dingbats.cff.c] Error 126
make[1]: Leaving directory '/media/ExtraDocuments/SwitchHacks/NX-Shell/mupdf'
make: *** [Makefile:151: generate_fonts] Error 2
```

maybe make it be able to compile without mupdf (because i don't care about the e-book reader personally) and i would like to build it locally

**Comment by joel16** [comment]
Weird, I'm using Ubuntu and it works just fine here. Did you make sure to follow the compiling instructions. Besides, I've set up travis to build and [deploy releases after each commit](https://github.com/joel16/NX-Shell/tree/gh-pages) so you don't necessarily need to build unless you plan on contributing.

**Comment by potjesoep** [comment]
i just did the exact same thing again and it works now, no idea why it wasn't working before
