### ISSUE TITLE
hide status bar reading ebook

### ISSUE THREAD

**Issue by SegFault42** [joel16/NX-Shell#21]
I think it's better for everyone to hide the status bar when i go to next or previous page.

**Comment by joel16** [comment]
Heh, I'm not too sure if that's a good idea. Seems more like a personal preference thing. I'll see what I can do.

**Comment by SegFault42** [comment]
That's the case in all android ebook reader app.

**Comment by SegFault42** [comment]
the status bar reappear when you touch the screen on the middle. I think it's not a problem to hide the status bar only when you go to prev or next page.

**Comment by joel16** [comment]
Ok that sounds reasonable, I'll take a look later or if you want feel free to PR :P

**Comment by joel16** [comment]
https://github.com/joel16/NX-Shell/commit/7c3dc7236e79e9fb4564c4c2458c4d51cc95887f 

Book reader no longer displays status bar after every page. Only displayed during zooming or if screen is touched in the middle or outside touch area depending on the orientation.
