### ISSUE TITLE
schermo nero con sx pro

### ISSUE THREAD

**Issue by donk3** [joel16/NX-Shell#22]
salve, ho notato che tutte le versioni di nx-shell sulla mia switch con firmware 5.1.0 e sx pro 1.4 non si avvia, mi appare solo una schermata nera, e sono costretto a tenere premuto il tasto accensione per spegnerla.
cosa puo essere??
grazie
----------------

hi, I noticed that all versions of nx-shell on my switch with firmware 5.1.0 and sx pro 1.4 does not start, I only get a black screen, and I have to hold down the power button to turn it off.
what can it be??
thank you

**Comment by joel16** [comment]
SX OS is not supported by homebrew developers. If you're using something like layeredFS you'll have to disable it.
