### ISSUE TITLE
The UI should not scroll when selecting a file or checkbox

### ISSUE THREAD

**Issue by Stone-D** [joel16/NX-Shell#26]
This behavior is disorienting, especially when multiple files are involved - files that had been selected earlier are then moved off-screen, introducing an element of doubt in the user's mind that can potentially lead to mental instability and a desire to Purge.

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/NX-Shell/commit/e71e036ee07b97e3dda195250f41b342f98ee756
