### ISSUE TITLE
regarding Image viewing 

### ISSUE THREAD

**Issue by ArielBerkovich** [joel16/NX-Shell#27]
Hi Joel, 
A big fan of nxshell, I am happy to know you switch from the vita scene to the switch.
I've noticed something weird about the whole zooming proccess.:It appears to be less and less smoth as the zooming gets bigger. I'm assuming thatll get fixed "on the fly" when you will be using opengl
Hw accelration, but maybe its not related and you can check that out? 

One more thing, when a user zooms a picture in , I think that he should be allowed to move the zoomed picture around to view different parts of it that he could not see had he not zoomed in the picture. 
much like in vitashell where you can use the right analoge to zoom and the left to move . 

I also think that the zoomed value should be reset to default everytime you advance for the next image to view on the directory. it just makes more sense imo. 

I know that I will really enjoy those changed, as it will make reading comic books and manga so much better ! 

Thanks for the work!

**Comment by joel16** [comment]
Sorry for the long wait, but this has been fixed now in master.
