### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by BenMitnicK** [joel16/NX-Shell#28]
Hi,
I tryed to compile ReiNXToolkit but I have an error see this issue https://github.com/Reisyukaku/ReiNXToolkit/issues/4

After that I installed 3 time Devkitpro but always the same error. But now I have this error when I tried to compile your code

C:/Users/BMK/switch/NX-Shell/source/menus/menu_book_reader/BookReader.cpp:6:10: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: BookReader.o] Error 1
make: *** [Makefile:159: build] Error 2

I looking for this file on the devkit or your code but no found it. you have a suggestion ??

**Comment by joel16** [comment]
You need to install libconfig for switch using devkitpro's pacman

**Comment by BenMitnicK** [comment]
it's true I had installed the switch modules and I just saw that no, it's my fault :(

THX
