### ISSUE TITLE
Zoon In Percentage

### ISSUE THREAD

**Issue by cirojr82** [joel16/NX-Shell#31]
Omg I couldn't believe when I found out that you could read books/magazines on the NSW! Great job!

I just noticed that you can't zoon in more than 209%, and I have some old game magazines that have pretty small fonts. So, is it possible to increse this zoom in percentage, would be great!

Thanks!

**Comment by joel16** [comment]
Due to several inconsistencies and lack of updates from the developer who initially PR'd the pdf/ebook reading part, it has been removed: db3de11
