### ISSUE TITLE
PDF Reader Black Screens

### ISSUE THREAD

**Issue by IAmBatby** [joel16/NX-Shell#38]
Reading Ms. Marvel, at least every issue, the pages start to just go plain back, restarting app fixes.

PDF Black screens, requires full NX-Shell restart

EPUB only requires backing in and out of the file, though they inconsistently load, most of them just have white pages with none of the actual content.

**Comment by joel16** [comment]
Due to several inconsistencies and lack of updates from the developer who initially PR'd the pdf/ebook reading part, it has been removed: db3de11
