### ISSUE TITLE
Dual Page Manga

### ISSUE THREAD

**Issue by NO-ob** [joel16/NX-Shell#39]
Feature Request Not an issue

I was wondering if it would be possible for you to add double page viewing for manga files since there is so much whitespace when the device is in landscape mode

**Comment by joel16** [comment]
Due to several inconsistencies and lack of updates from the developer who initially PR'd the pdf/ebook reading part, it has been removed: https://github.com/joel16/NX-Shell/commit/db3de114bc51b738c7f54066bf5b211d8c14a619
