### ISSUE TITLE
Please can you work on Rename next?

### ISSUE THREAD

**Issue by a7mag3ddon** [joel16/NX-Shell#4]
Please can you work on renaming folders next, would be really usefull for the titleID swap trick.

**Comment by benji28380** [comment]
good job, but ,pleaaaaase make a patch for renaming option! :,(

**Comment by joel16** [comment]
Apologize for the delay, I have been busy with IRL stuff. 
Anyways this is going to come next as I have finally included by own OSK. https://github.com/joel16/NX-Shell/commit/100d60085383e26da2213138cc54f75a33394a61 It doesn't look all that great but it does the job. Still need to clean some things up, but the next beta release should happen sometime this week.
