### ISSUE TITLE
Crash happened after delete the folder in "lastdir.txt"

### ISSUE THREAD

**Issue by dubyoo** [joel16/NX-Shell#40]
1. Enter NX-Shell
2. Open one directory like "/tinfoil/nsp/Overcooked/"
3. Exit NX-Shell and generate "lastdir.txt"
4. Delete directory "/tinfoil/nsp/Overcooked/" by tftp or some other ways
5. Enter NX-Shell again
Then Atmosphere crash happened. Only restart and delete the file "lastdir.txt" can fix it.

**Comment by joel16** [comment]
Odd, I thought I had this covered. Will look into it in the morning.

**Comment by joel16** [comment]
Are you sure you're using the latest release? I can't seem to reproduce this. It should be handled here: https://github.com/joel16/NX-Shell/blob/master/source/config.c#L100

**Comment by dubyoo** [comment]
I download the latest release and the problem was fixed, Thank you!
