### ISSUE TITLE
ftp very slow

### ISSUE THREAD

**Issue by wududu123** [joel16/NX-Shell#42]
Why is the transmission speed very slow?

**Comment by joel16** [comment]
Hey sorry to hear that, what sorts of speeds are you getting?

**Comment by wududu123** [comment]
Only 3MB/s. But I download from eshop is more than  5MB/s.
SD card writting speed 50MB/s.

**Comment by joel16** [comment]
IIRC, I believe all dl speeds are like that with the Switch at the moment.

**Comment by wududu123** [comment]
ok, ths!
