### ISSUE TITLE
/switch folder

### ISSUE THREAD

**Issue by adamarsx** [joel16/NX-Shell#44]
6.2 Atmopshere, using MacOS Mojave to transfer files.
NX-Shell can't open the /switch folder (neither can hbmenu), all folders can be opened without problem. Nothing happens when trying to delete the folder, I've also tried deleting the folder from my Mac but NX-Shell also can't create a new one after that. There's a 0B file called SWITCH, which I also can't delete. I'm currently running all .nro files from the root of my SD as the /switch folder isn't recognized. I've tried disabling the archive bit from a Windows VM, MacOS Terminal and with the Hekate archive bit remover, but nothing works. I also tried deleting the folder from Windows and creating a new one, which also doesn't work.

**Comment by joel16** [comment]
Might want to backup your data in your SD and then format it using windows and then start fresh to see if it helps. Apart from that I have no idea.
