### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by wang93wei** [joel16/NX-Shell#46]
I hope to support multiple languages, thank you.

**Comment by joel16** [comment]
Yes this is possible, but translations will need to be made somewhere.
Also I only plan on supporting the official Nintendo supported languages.

**Comment by wang93wei** [comment]
Thanks. Switch 7.0 now supports Chinese. You can find a translation platform.

**Comment by agarcialeon** [comment]
I recommend to use Crowdin as translatiion platform. I have been using it for Beat Saber Wiki and it has a free plan and it accepts contributions by login in with the Github account.

**Comment by joel16** [comment]
There is an issue tracker for this: https://github.com/joel16/NX-Shell/issues/87. I will update it shortly.
