### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by eALduderino** [joel16/NX-Shell#47]
Hey guys.
Yesterday I restored and Reinstalled my Switch.
I'm running FW 5.1.0 with SanDisk Extreme 128GB, on which i installed the latest SD Setup and SXOS 2.6.1 beta. I use the emuNAND and updated the CFW to 7.0.1.
When i started installiung stuff and usiong NX-Shell (latest update) it ctrashed randomly.
sometimes after deleting data and folders, sometimes after moving stuff, sometimes afetr moving through directories and one time directly when starting the app in hbmenu. Causing the need to reboot the switch.
any hints or advice?
Theanks

**Comment by joel16** [comment]
I'm assuming you're using exfat?

**Comment by eALduderino** [comment]
yes you are assuming quite right!. Ist that causing issues?

**Comment by joel16** [comment]
As far as I'm concerned exFAT doesn't work well with homebrew. https://gbatemp.net/threads/poll-fat32-vs-exfat-issue-discussion.514801/

**Comment by fennectech** [comment]
Nintendo’s exfat driver loves to corrupt data.

**Comment by eALduderino** [comment]
Huh, ain‘t that something! Ok thanks for the update guys. My filesystem just got corrupted, again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eALduderino** [comment]
Time to switch back to fat32

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joel16** [comment]
Closing this for now.
