### ISSUE TITLE
Consistent fatal on 7.0.1 when force terminating with usb plugged in

### ISSUE THREAD

**Issue by averne** [joel16/NX-Shell#48]
NX-Shell consistently makes usb (`01...0006`) throw a `0x0` fatal when force terminating (ie pressing home without first going back to hbmenu), if the console is plugged in a computer.
[Fatal report](https://pastebin.com/6gGni0Wh).

**Comment by joel16** [comment]
This seems to be an issue with libnx. I will look into this in the coming days.

**Comment by joel16** [comment]
Can you try with this? https://github.com/joel16/NX-Shell/blob/gh-pages/NX-Shell.nro

**Comment by averne** [comment]
This seems to be working. On the other hand, I can't reproduce with the old version, having updated to 8.0.0 in-between.

**Comment by uaevuon** [comment]
I tested new .nro file and it works.

I'm on 7.0.1 with atmosphere 0.8.8

1.2.0 has usb crash error, but new file works fine.

**Comment by joel16** [comment]
Use the version linked above for now until a new release is up.
