### ISSUE TITLE
Full black screen crash on 7.0.x, clean install, without usb

### ISSUE THREAD

**Issue by tantoinet** [joel16/NX-Shell#49]
On 7.0.0 and 7.0.1, the nx-shell crashes totally the console with a black screen when leaving the app through the HOME button.
The crash happens regardless USB (dis)connection state.

Tested on a clean system, no nsp installed and running ReiNX 2.1.1 + 128gb sandisk sdcard from Amazon.

No workaround found.

**Comment by joel16** [comment]
Can you try with this? https://github.com/joel16/NX-Shell/blob/gh-pages/NX-Shell.nro

**Comment by joel16** [comment]
Fixed.
