### ISSUE TITLE
Only works for a single RCM session

### ISSUE THREAD

**Issue by a7mag3ddon** [joel16/NX-Shell#5]
Hopefully i can explain this fully.

I can only run NX-Shell once per RCM session, by that i mean, i can boot switch into RCM then firmware, i then run NXShell no problem. Start a game, plays fine, press home to go back to home screen and close the running game. press album and select nxshell and either a) it crashes with an error on screen or b) i just get a black screen.

Pressing home doesnt go back to the home screen and i have to turn it off.

Turning back on in RCM mode and booting to home screen then allows me to run nx shell again fine.

**Comment by chronoss09** [comment]
I have the same problem, for me, i have the black screen but i can return to home screen witch home bouton...

**Comment by joel16** [comment]
Are you guys using layered FS or anything? This definitely isn't a problem with NX Shell because it works fine here as long as you're using just the homebrew launcher.

**Comment by a7mag3ddon** [comment]
Yes I am using layeredFS.

It's not that it doesn't work, it does. Just doesn't run more than once.

**Comment by joel16** [comment]
That's my point.. This isn't a problem with NX-Shell sorry.
