### ISSUE TITLE
Retroarch crashes after quit nx-shell

### ISSUE THREAD

**Issue by uaevuon** [joel16/NX-Shell#51]
Don't know it's nx-shell's problem or retroarch's, so I report on both side.

atmosphere 0.9.1, fat32
Tried on both sys 8.1.0 and emummc 8.0.1

retroarch keeps crashing when trying to quit retroarch

1. launch homebrew through album or game (does not matter)
2. launch nx-shell and quit with plus button
3. launch retroarch and quit with Quit Retroarch menu
4. crash

Here's my atmosphere crash report logs.
[logs.zip](https://github.com/joel16/NX-Shell/files/3313011/logs.zip)

**Comment by joel16** [comment]
Should (hopefully) be fixed with the following commit: https://github.com/joel16/NX-Shell/commit/fbf1b54b8696178488731b80a888085f5e0d4986

Edit: Tested on my device, it previously would crash before but after this commit it no longer does.
