### ISSUE TITLE
7z decompression hangs

### ISSUE THREAD

**Issue by muxi1** [joel16/NX-Shell#52]
The attempt to decompress a 7z archive did not work. It appeared even after a long time of waiting no progress bar

**Comment by joel16** [comment]
How large was the file?

**Comment by muxi1** [comment]
It was one of the Retroarch Nigthy builds with a size of about 171 MB.  After a waiting time of about 10 minutes I canceled the process. With a recompression to zip (about 464 MB) it worked. (like already under the older versions of NX-Shell)

**Comment by joel16** [comment]
Unfortunately 7z decompression has been removed from most recent releases. Going forward I'm only going to be supporting zip files for now.
