### ISSUE TITLE
crashes when trying to enable developer tools

### ISSUE THREAD

**Issue by mexxs** [joel16/NX-Shell#54]
Just like the title says NX-Shell crashes when I try to enable the developer tools. I tried it on 8.1.0 (0.9.2-AMS) in EmuNand and on 4.1.0 (0.9.2-AMS) SysNand. 
Atmosphere error code: 2168-002 (0x4a8)
EDIT:
tested with NX-Shell version 1.20 and 2.00
I'd only need it to set the archive bit. Is there any way to do that without activating developer tools?

**Comment by joel16** [comment]
Are you using exFAT?

**Comment by mexxs** [comment]
No I'm using FAT32. I found a solution that doesn't require me to set the archive bit. But I'd be glad to help with providing more information if I can.

**Comment by joel16** [comment]
It's weird because 0x4a8 usually refers to an abnormal process termination via svcExitProcess. I'm not sure how you came up with a solution but I assume its by manually editing the config file? Also could you perhaps try the latest nightly and see if the issue still persists? https://github.com/joel16/NX-Shell/blob/gh-pages/NX-Shell.nro

**Comment by mexxs** [comment]
Since fluffy works now on Mac with goldtree I don't need to set archive bits anymore. I just wanted to do that with NX-Shell because macOS apparently doesn't do it even when using the appropriate chflags command. 
I'll gladly try the latest nightly and get back to you!

**Comment by mexxs** [comment]
Same behavior with the one from your link. Maybe it's an hb-menu error? I can only load NROs from the /emuMMC/RAW1/switch folder and not from the /switch folder. The root switch folder won't open in hb-menu for some reason. Both folders are on the FAT32 partition though. It doesn't make a difference if I boot into emuNand or sysNand.

**Comment by joel16** [comment]
That might be a problem. It needs to read/write data to the /switch folder. It's not being able to do that when you enable developer options (writes to a config file so it remembers the next time you launch NX-Shell) therefore it's crashing.

**Comment by mexxs** [comment]
I see. Maybe I'll look into why it can't access the /switch folder. You can close this I guess since it's not an NX-Shell issue. Thanks anyway! :)
