### ISSUE TITLE
file operation menu issue after choosing "More"

### ISSUE THREAD

**Issue by WanderMax** [joel16/NX-Shell#60]
1. mark one file and press '...' to open file operation menu, it pops action menu 1
2. choose "More" to see  action menu 2
3. tap 'cancel' to exit action menu
4. press '...' again to view action menu, now it always be menu 2, can't be menu 1
Ver 2.00, I think it should be bug, it can be produced in my NS with Kosmos-v13.2.1 (8.01)

![menu1](https://user-images.githubusercontent.com/15909056/65831910-d67c2780-e2f0-11e9-9bc7-ac9994719b13.jpg)
![menu2](https://user-images.githubusercontent.com/15909056/65831909-d5e39100-e2f0-11e9-9dc3-1e9728fcced9.jpg)

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/NX-Shell/commit/00e7094fd759c22119f29751926427bcd50b6b47
