### ISSUE TITLE
Crashes on 9.0.0

### ISSUE THREAD

**Issue by simplyimpossible** [joel16/NX-Shell#61]
I'm on Atmosphere-Kosmos with the latest version (Switch firmware 9.0.0), and I have NX-Shell with the latest version as well. When opening, I get a crash with a orange screen. When I use fusee-primary, it crashes without an orange screen (with the backlight still on). It happens at random times because I opened it once on Kosmos and it worked fine. Opened it again and got the said orange screen.

**Comment by joel16** [comment]
Can you try: https://github.com/joel16/NX-Shell/releases/tag/2.10

**Comment by simplyimpossible** [comment]
Thank you.
