### ISSUE TITLE
Operation bug in version 2.1.0

### ISSUE THREAD

**Issue by muxi1** [joel16/NX-Shell#62]
It seems that under version 2.1.0 different operations like delete or move can not always be done correctly. I tested this under FW 9.0.0. Version 2.0.0, however, runs without problems under FW 9.0.0.
This screen shows an error message when deleting a folder
![2019093011260000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/39792666/65866555-49c77d00-e375-11e9-8a36-1d9bb58ac1d8.jpg)

Also, data under version 2.1.0 can not be moved anymore. 
Tested unter Atmospére 0.9.4 partition emuMMC & SX OS 2.9 beta filebased emuNand, both on FW 9.0.0

**Comment by joel16** [comment]
Are you launching this from applet?

**Comment by muxi1** [comment]
Yes, from hbmenu in applet mode.

I'll test it via nsp injection ..... the same here too

under version 2.0.0 everything runs fine, both over nsp -injektion, as well as in applet mode

**Comment by joel16** [comment]
Can you try running it from a game instead of applet? I'm not talking about nsp injection by the way.

**Comment by muxi1** [comment]
Is nsp injection not the same as running hbmenu over an installed title (game)? That's exactly what I've already tried. At least no more applet mode is displayed in the hbmenu, if I start it this way, but the problem under v2.1.0 persists.

**Comment by joel16** [comment]
I'm not sure. I have never messed around with nsp. Anyways I'll take a look and see if this affects my device later today.

**Comment by muxi1** [comment]
I find it interesting that the v2.0.0 under FW 9.0.0 runs smoothly, where other HB tools fail in this regard. Thank you for taking on this problem.

**Comment by joel16** [comment]
Please try the latest release [v2.11](https://github.com/joel16/NX-Shell/releases/tag/2.11).

**Comment by muxi1** [comment]
The problem is now solved with v2.1.1! Thank you so much!
