### ISSUE TITLE
2.10 - Can't move/copy/delete or files.

### ISSUE THREAD

**Issue by jordaninthesky** [joel16/NX-Shell#63]
Nothing happens.  No error.  Confirmation prompt pops, but nothing changes in the file-structure.  Renaming works for me, though.

I am on latest Atmosphere and FW versions, to date.  2.00 still works for me.

**Comment by joel16** [comment]
Thanks for letting me know! However, this is a duplicate of https://github.com/joel16/NX-Shell/issues/62. Please follow that issue until a fix is pushed.

**Comment by jordaninthesky** [comment]
Oops, my mistake.  Saw the screenshot and thought it was about renaming.
