### ISSUE TITLE
Archive bit failed on 2.11

### ISSUE THREAD

**Issue by simplyimpossible** [joel16/NX-Shell#66]
Error message when pressing set archive bit on a selected folder.

FS_SetArchiveBit() failed!
Ret:0x202

Happens both on Vanilla Atmosphere 9.4 and Kosmos 14.2

**Comment by joel16** [comment]
Does this only happen with 2.11?

**Comment by simplyimpossible** [comment]
It happens to both 2.11 and 2.10, which leads me to believe it might be a problem on my end. This error message happens with almost every folder I select, and it isn't tied to one specific folder.
I also switched from Kosmos 14.2 to 14.1 and I still get the same error. I don't know anymore.
I've tried unseting archive bits via Hekate but that didn't do much. I might just close this since it doesn't really seem like a problem with the program...

**Comment by Powerbless** [comment]
for me the same...error

**Comment by Powerbless** [comment]
oh now it works! i redownload it because the version where i had was a litle bit bigger in size. then i startet nx-shell and go to the *.nsp folger, marked the box before the folder und click the 3 points on top right. then properties->set archive bit......and....NO error :-)
