### ISSUE TITLE
2.1.1 NSP Forwarder has no button input

### ISSUE THREAD

**Issue by metal1one** [joel16/NX-Shell#68]
I believe you need to update libnx and recompile the 2.1.1 release. It works with atmos thru album but not forwarder due to the 9.0.0 update.

**Comment by joel16** [comment]
The latest version is re-compiled with the latest libnx. Also you're not supposed to be booting through album.

**Comment by metal1one** [comment]
I thought it was recompiled with latest, but for whatever reason, it has no button input using a forwarder. I recompiled it myself and it works now though.

**Comment by joel16** [comment]
I thought NSPs aren't recommended in the homebrew community?

**Comment by metal1one** [comment]
I use whatever works best and is most convenient for me. But it s all good now. Not sure why the latest release wasnt working through the forwarder.
