### ISSUE TITLE
7z decompression leads to corrupted data

### ISSUE THREAD

**Issue by muxi1** [joel16/NX-Shell#69]
Hi @joel16 
Although the data of a 7z archive is unpacked under NX-Shell version 2.1.1 without error message, files are corrupted afterwards. I noticed this in the example of the Retroarch Loader NRO from the release's 7z package, after I got the unpacked nro file displayed without icon in the homebrew menu, and the console crashed while trying to run it. With the same file unpacked from a ZIP archive this is not the case.

**Comment by joel16** [comment]
Unfortunately 7z decompression has been removed from most recent releases. Going forward I'm only going to be supporting zip files for now.
