### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by LavaJockey** [joel16/NX-Shell#70]
fs.c
aarch64-none-elf-gcc -MMD -MP -MF /c/NX-Shell/build/fs.d -g -Wall -O3 -ffunction-sections -DVERSION_MAJOR=2 -DVERSION_MINOR=1 -DVERSION_MICRO=1 -DAPP_TITLE="\"NX-Shell\"" -DGITVERSION="\"1f1e378\"" -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -D__SWITCH__ -I/c/NX-Shell/include -I/c/NX-Shell/include/audio -I/c/NX-Shell/include/ftp -I/c/NX-Shell/include/gif -I/c/NX-Shell/include/menus -I/c/NX-Shell/libs/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/NX-Shell/libs/include -I/opt/devkitpro/portlibs/switch/include/opus -I/opt/devkitpro/libnx/include/opus -I/c/NX-Shell/libs/include/opus -I/c/NX-Shell/build `freetype-config --cflags` `sdl2-config --cflags` -c /c/NX-Shell/source/fs.c -o fs.o
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c: In function 'FS_FileExists':
C:/NX-Shell/source/fs.c:17:46: error: 'FS_OPEN_READ' undeclared (first use in this function)
   17 |  if (R_SUCCEEDED(fsFsOpenFile(fs, temp_path, FS_OPEN_READ, &file))) {
      |                                              ^~~~~~~~~~~~
C:/NX-Shell/source/fs.c:17:46: note: each undeclared identifier is reported only once for each function it appears in
C:/NX-Shell/source/fs.c: In function 'FS_DirExists':
C:/NX-Shell/source/fs.c:31:51: error: 'FS_DIROPEN_DIRECTORY' undeclared (first use in this function)
   31 |  if (R_SUCCEEDED(fsFsOpenDirectory(fs, temp_path, FS_DIROPEN_DIRECTORY, &dir))) {
      |                                                   ^~~~~~~~~~~~~~~~~~~~
C:/NX-Shell/source/fs.c: In function 'FS_GetDirEntryCount':
C:/NX-Shell/source/fs.c:90:45: warning: pointer targets in passing argument 2 of 'fsDirGetEntryCount' differ in signedness [-Wpointer-sign]
   90 |  if (R_FAILED(ret = fsDirGetEntryCount(dir, count))) {
      |                                             ^~~~~
      |                                             |
      |                                             u64 * {aka long unsigned int *}
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:402:42: note: expected 's64 *' {aka 'long int *'} but argument is of type 'u64 *' {aka 'long unsigned int *'}
  402 | Result fsDirGetEntryCount(FsDir* d, s64* count);
      |                                     ~~~~~^~~~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c: In function 'FS_ReadDir':
C:/NX-Shell/source/fs.c:103:36: warning: passing argument 2 of 'fsDirRead' makes pointer from integer without a cast [-Wint-conversion]
  103 |  if (R_FAILED(ret = fsDirRead(dir, inval, total_entries, max_entries, entry))) {
      |                                    ^~~~~
      |                                    |
      |                                    u64 {aka long unsigned int}
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:401:33: note: expected 's64 *' {aka 'long int *'} but argument is of type 'u64' {aka 'long unsigned int'}
  401 | Result fsDirRead(FsDir* d, s64* total_entries, size_t max_entries, FsDirectoryEntry *buf);
      |                            ~~~~~^~~~~~~~~~~~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c:103:43: warning: passing argument 3 of 'fsDirRead' makes integer from pointer without a cast [-Wint-conversion]
  103 |  if (R_FAILED(ret = fsDirRead(dir, inval, total_entries, max_entries, entry))) {
      |                                           ^~~~~~~~~~~~~
      |                                           |
      |                                           size_t * {aka long unsigned int *}
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:401:55: note: expected 'size_t' {aka 'long unsigned int'} but argument is of type 'size_t *' {aka 'long unsigned int *'}
  401 | Result fsDirRead(FsDir* d, s64* total_entries, size_t max_entries, FsDirectoryEntry *buf);
      |                                                ~~~~~~~^~~~~~~~~~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c:103:58: warning: passing argument 4 of 'fsDirRead' makes pointer from integer without a cast [-Wint-conversion]
  103 |  if (R_FAILED(ret = fsDirRead(dir, inval, total_entries, max_entries, entry))) {
      |                                                          ^~~~~~~~~~~
      |                                                          |
      |                                                          size_t {aka long unsigned int}
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:401:86: note: expected 'FsDirectoryEntry *' {aka 'struct <anonymous> *'} but argument is of type 'size_t' {aka 'long unsigned int'}
  401 | Result fsDirRead(FsDir* d, s64* total_entries, size_t max_entries, FsDirectoryEntry *buf);
      |                                                                    ~~~~~~~~~~~~~~~~~~^~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c:103:21: error: too many arguments to function 'fsDirRead'
  103 |  if (R_FAILED(ret = fsDirRead(dir, inval, total_entries, max_entries, entry))) {
      |                     ^~~~~~~~~
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:401:8: note: declared here
  401 | Result fsDirRead(FsDir* d, s64* total_entries, size_t max_entries, FsDirectoryEntry *buf);
      |        ^~~~~~~~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c: In function 'FS_GetFileSize':
C:/NX-Shell/source/fs.c:120:49: error: 'FS_OPEN_READ' undeclared (first use in this function)
  120 |  if (R_FAILED(ret = fsFsOpenFile(fs, temp_path, FS_OPEN_READ, &file))) {
      |                                                 ^~~~~~~~~~~~
C:/NX-Shell/source/fs.c:129:42: warning: pointer targets in passing argument 2 of 'fsFileGetSize' differ in signedness [-Wpointer-sign]
  129 |  if (R_FAILED(ret = fsFileGetSize(&file, size))) {
      |                                          ^~~~
      |                                          |
      |                                          u64 * {aka long unsigned int *}
In file included from D:/devkitPro/libnx/include/switch.h:49,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
D:/devkitPro/libnx/include/switch/services/fs.h:396:38: note: expected 's64 *' {aka 'long int *'} but argument is of type 'u64 *' {aka 'long unsigned int *'}
  396 | Result fsFileGetSize(FsFile* f, s64* out);
      |                                 ~~~~~^~~
In file included from D:/devkitPro/libnx/include/switch.h:13,
                 from C:/NX-Shell/include/common.h:4,
                 from C:/NX-Shell/source/fs.c:6:
C:/NX-Shell/source/fs.c: In function 'FS_ReadFile':
C:/NX-Shell/source/fs.c:232:49: error: 'FS_OPEN_READ' undeclared (first use in this function)
  232 |  if (R_FAILED(ret = fsFsOpenFile(fs, temp_path, FS_OPEN_READ, &file))) {
      |                                                 ^~~~~~~~~~~~
C:/NX-Shell/source/fs.c:241:53: error: 'FS_READOPTION_NONE' undeclared (first use in this function)
  241 |  if (R_FAILED(ret = fsFileRead(&file, 0, buf, size, FS_READOPTION_NONE, &out))) {
      |                                                     ^~~~~~~~~~~~~~~~~~
C:/NX-Shell/source/fs.c: In function 'FS_WriteFile':
C:/NX-Shell/source/fs.c:281:49: error: 'FS_OPEN_WRITE' undeclared (first use in this function)
  281 |  if (R_FAILED(ret = fsFsOpenFile(fs, temp_path, FS_OPEN_WRITE, &file))) {
      |                                                 ^~~~~~~~~~~~~
C:/NX-Shell/source/fs.c:290:67: error: 'FS_WRITEOPTION_FLUSH' undeclared (first use in this function)
  290 |  if (R_FAILED(ret = fsFileWrite(&file, 0, buf, size + len, flush? FS_WRITEOPTION_FLUSH : FS_WRITEOPTION_NONE))) {
      |                                                                   ^~~~~~~~~~~~~~~~~~~~
C:/NX-Shell/source/fs.c:290:90: error: 'FS_WRITEOPTION_NONE' undeclared (first use in this function)
  290 |  if (R_FAILED(ret = fsFileWrite(&file, 0, buf, size + len, flush? FS_WRITEOPTION_FLUSH : FS_WRITEOPTION_NONE))) {
      |                                                                                          ^~~~~~~~~~~~~~~~~~~
C:/NX-Shell/source/fs.c: In function 'FS_SetArchiveBit':
C:/NX-Shell/source/fs.c:319:21: warning: implicit declaration of function 'fsFsSetArchiveBit'; did you mean 'FS_SetArchiveBit'? [-Wimplicit-function-declaration]
  319 |  if (R_FAILED(ret = fsFsSetArchiveBit(fs, temp_path))) {
      |                     ^~~~~~~~~~~~~~~~~
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:19: fs.o] Error 1
make: *** [Makefile:153: build] Error 2

**Comment by lavaJockey** [comment]
Recently fresh install of all libs and devkitpro

**Comment by joel16** [comment]
Needs to be updated for latest version of libnx.
