### ISSUE TITLE
Kernel Panic on enabling Dev Mode

### ISSUE THREAD

**Issue by LilaQ** [joel16/NX-Shell#71]
Hi, I'm getting a Kernel Panic as soon as I try to enable Dev Mode. 
HOS 9.1, latest Atmosphere, latest NX-Shell

**Comment by joel16** [comment]
Hey, sorry to say but this project is currently suspended. I'm busy working on other things right now and I can't say when I'll get back to this, if ever.

**Comment by AnalogMan151** [comment]
Damn. I'm getting a kernel panic when trying to enable archive bit on Atmo 0.10.4. This was the only tool I could use to do that since I don't have Windows and Mac can't set flags on a FAT32 file system. Hmmm.

EDIT: GoldLeaf has this ability now too and works fine. So I'm good for now.

**Comment by Masamune3210** [comment]
I believe hekate also can fix archive bits, unless you were talking about split nsps

**Comment by joel16** [comment]
This is no longer a thing in the current release.
