### ISSUE TITLE
Pictures not being able to display properly.

### ISSUE THREAD

**Issue by BlackFrankFTM2** [joel16/NX-Shell#72]
Hi!

I have an issue in which NX-Shell loads up to two pictures before it goes completely black, and in some cases will fail to even display a picture at all. Even with GIFs that are large in size, the program will struggle to load them and will either:

a) Crash the Switch (if running in Album Mode)
b) Crash the HBMenu (if running in NSP mode)

If there's anything I can do to fix this, let me know! NX-Shell is a good file manager and I don't want to lose one of my most favorite capabilities.

Edit: I'm running SX OS 2.9.2 on firmware 9.0.1.

**Comment by joel16** [comment]
Hey, sorry to say but this project is currently suspended. I'm busy working on other things right now and I can't say when I'll get back to this, if ever.

**Comment by joel16** [comment]
Should no longer be an issue with the most recent release.
