### ISSUE TITLE
Kosmos v15.1 hid-mitm removal breaks support

### ISSUE THREAD

**Issue by ghost** [joel16/NX-Shell#75]
Controls do not work

**Comment by joel16** [comment]
I am not associated with Kosmos, however apparently this one works. https://github.com/octopuserectus/NX-Shell/releases/tag/2.11-1

**Comment by gut5** [comment]
It's not really a Kosmos thing, the OP should have said how hid-mitm removal happened in AMS.

**Comment by ghost** [comment]
Correct. Atmosphere changelog says temporary hid-mitm was disabled on latest release and can be enabled while latest Kosmos release refers to Atmosphere's changelog and says it was removed. That's where the confusion was coming from, difference in syntax. Nonetheless, I can confirm v2.11-1 works without adding "enable_deprecated_hid_mitm". Thanks.
