### ISSUE TITLE
Wierd display wierdness 

### ISSUE THREAD

**Issue by fennectech** [joel16/NX-Shell#78]
![2020041421485000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/11953665/79293643-de20a980-7e99-11ea-8a94-40fb99bb7c86.jpg)
![2020041421482200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/11953665/79293645-e0830380-7e99-11ea-9869-f10d6c922228.jpg)

Deleted all the logs and config after updating it.

**Comment by fennectech** [comment]
config.json `{
	"config_ver": 0,
	"sort": 0,
	"dark_theme": 1,
	"last_dir": "/"
}`

imgui.ini

`[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][NX-Shell]
Pos=60,60
Size=32,100
Collapsed=0`

**Comment by Zidapi82** [comment]
The new default settings aren’t set up correctly, it’s an easy fix for the dev.

In the meantime make the following adjustments to the [Window][NX-Shell] entry in the imgui.ini to restore functionality.

[Window][NX-Shell]
Pos=0,0
Size=1280,720
Collapsed=0

**Comment by joel16** [comment]
> The new default settings aren’t set up correctly, it’s an easy fix for the dev.

Actually it is set-up. It was always working fine for me on an older version of imGui. It's just that my imGui config didn't change when I applied the newer versions, and at some point it broke.
https://github.com/joel16/NX-Shell/blob/next/source/gui.cpp#L308

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/NX-Shell/commit/646da45c5f7ca81b99317e0efd712959214bf234
