### ISSUE TITLE
Not work on last atmosphere

### ISSUE THREAD

**Issue by chronoss09** [joel16/NX-Shell#79]
Nothing work on the last atmosphere :(

**Comment by joel16** [comment]
Which one? The new beta or old version?

**Comment by chronoss09** [comment]
Sorry, i use the old one (3.0.0), the last one work very well i like the new design but, i can't open music and picture file :(

**Comment by joel16** [comment]
Try this? https://github.com/joel16/NX-Shell/blob/gh-pages/NX-Shell.nro

**Comment by diolos** [comment]
What happened to the touchscreen and ftp? It lost almost all of the features

**Comment by Masamune3210** [comment]
![Screenshot_20200507-094600](https://user-images.githubusercontent.com/1053504/81308607-98de3a80-9047-11ea-9068-ed828de19e74.jpg)

**Comment by llamasoft** [comment]
Well dang.  I wish the version in the Homebrew App Store hadn't been updated.  It doesn't provide a downgrade function, so now anyone attempting upgrading or installing it fresh is going to think it's broken.

**Comment by joel16** [comment]
Please use the most recent release.
