### ISSUE TITLE
FTP? or USB MSC?

### ISSUE THREAD

**Issue by fennectech** [joel16/NX-Shell#8]
Would you be able to implement FTP or USBMSC?

**Comment by kenshin088** [comment]
USB support would be a game changer! Not sure how feasible it is though

**Comment by fennectech** [comment]
They did it on the vita.    SO it should be possable.  
https://github.com/TheOfficialFloW/VitaShell/blob/master/usb.c   Heres their implimentation of USBMSC

**Comment by joel16** [comment]
The switch and vita have almost nothing in common. There's no plugin framework like taiHen or any sort of plugins ATM. For now we could write our own sysmodules, idk what else has been made available. Things are still pretty early as I understand it.

**Comment by fennectech** [comment]
Their USBMSC was nto a plugin but a feature in a homebrew.       A sysmodule that proivides USBMSC would be totally amazing.

**Comment by joel16** [comment]
@fennectech the homebrew is loading the plugin https://github.com/TheOfficialFloW/VitaShell/blob/master/usb.c#L143

**Comment by fennectech** [comment]
Ahh.  :/

**Comment by ValShaped** [comment]
IIRC, Horizon doesn't actually do anything with USB when the system is undocked, and doesn't mind if you take it over? See https://github.com/yellows8/switch_sysmodule

**Comment by fennectech** [comment]
Wow.  :D.   @joel16    Sysmodules are basicly plugins right?   Daemons that run in the background and are loaded on boot?

**Comment by ValShaped** [comment]
Sysmodules are like kernel extensions running in userspace. They can only, with a few exceptions, do what userspace applications can do. As long as nothing else is using the USB port, I don't see why it'd be impossible to do, just difficult.

**Comment by ttimasdf** [comment]
There are other projects implementing [FTP](https://github.com/jakibaki/sys-ftpd) and [MSC](https://github.com/retronx-team/mtp-server-nx) nowadays.

**Comment by DarkMatterCore** [comment]
fs services offer no way to access the SD card as a raw block device. It'd be very difficult, if not impossible, to add a live UMS mode to any homebrew apps running under Horizon OS. The best option for this nowadays is Hekate's UMS feature.

FTP, SMB and other network protocols should be doable, though, as well as [adding support for UMS devices](https://github.com/DarkMatterCore/libusbhsfs).

**Comment by fennectech** [comment]
Howabout MTP

**Comment by DarkMatterCore** [comment]
@fennectech Doable as well. Unlike UMS, MTP doesn't require the device to provide the USB host with full, locked access to the raw block device. It's filesystem agnostic and it works even if the device needs to use the storage medium at the same time.

**Comment by fennectech** [comment]
This is the best option as it allows the performance of USB.
