### ISSUE TITLE
error occur under 10.0.4

### ISSUE THREAD

**Issue by tempest132** [joel16/NX-Shell#81]
error occur under sxos 3.0.0; ns version 10.0.4 

Error  Code: 2144-0001

**Comment by tempest132** [comment]
forgot to mention, I used NX-Shell v3.01, when install it, the error report~

**Comment by spling-du-futur** [comment]
@tempest132 update your SX OS!
me too i have the problem, tried sx os menu, applet mode, hbmenu redirection (holding R on an app then start)
when i boot nxshell 2168-0002 fatal error
