### ISSUE TITLE
FSP USB support?

### ISSUE THREAD

**Issue by bqio** [joel16/NX-Shell#83]
Will there be FSP USB support?

**Comment by oxley192** [comment]
Really hope this does get fsp-usb support and I hope it get a video playback aswell Again cause I loved it when it had video playback on it before

**Comment by DarkMatterCore** [comment]
Just a heads up: fsp-usb has been superseded by [libusbhsfs](https://github.com/DarkMatterCore/libusbhsfs). No one should use fsp-usb anymore.

**Comment by fennectech** [comment]
Is libusbhsfs gonna are it into this tool?
