### ISSUE TITLE
Moving homebrew files corrupted my sd card

### ISSUE THREAD

**Issue by JHumBL3** [joel16/NX-Shell#85]
I was copying files from one folder to another. Using atmosphere. Switch crashed and was no longer able to boot into Atmos or play games from SD card using sxos. Corrupted errors. Using newest atmos and fw 10.1.0

**Comment by joel16** [comment]
Do you have any logs? Crash dumps? Also is this based on the most recent release? Just so you know the "rename" functionality apparently doesn't work on SX OS, which is basically what 'move' does. Rename file from path a -> path b. However you're saying you used atmosphere so I'm not sure.

Regardless I have tested these builds multiple times before pushing them out. Please give me more info.

**Comment by joel16** [comment]
Closing due to lack of response.
