### ISSUE TITLE
FTP option can't be found in NX-Shell

### ISSUE THREAD

**Issue by IISAKNIFE** [joel16/NX-Shell#94]
I have been using an older version of NX-Shell for a while. I just updated, and the option for the ftp server is gone. FTP is my primary use of NX-Shell, so the latest release is unusable for me.

**Comment by Electric1447** [comment]
Use ftpd untill joel updates NX-Shell

**Comment by joel16** [comment]
It was removed because its essentially the same thing as FTPD.

**Comment by NWPlayer123** [comment]
> It was removed because its essentially the same thing as FTPD.

That's a shame, I've been waiting for it to be added in the rewrite for years, still running a modded 2.1.1 I made for the controls fix
