### ISSUE TITLE
Renaming isn't working

### ISSUE THREAD

**Issue by 20Phoenix** [joel16/NX-Shell#95]
Hi.
I noticed that renaming isn't working.
After selecting "Rename" it just closes the options and goes back to the list.
Sure I had selected files by hook a file.
Not sure if new FW 11.0 is the reason because I haven't used it before.
Could it be that a rebuild using new libnx is needed ?

**Comment by joel16** [comment]
Just to be sure how are you launching this? Is it through app mode or applet?

**Comment by GitEz-code** [comment]
I found a solution, we have to launch NX-shell in appmode. in applet it doesn't work.
