### ISSUE TITLE
NX Shell crashes on new 1TB card

### ISSUE THREAD

**Issue by haywire27** [joel16/NX-Shell#96]
I just upgraded from 400GB to 1TB card.

All content is the same on the 1TB card as old 400gb (drag-and-dropped data from one card to the other), formatted FAT32 (default allocation file size).  But NX Shell crashes often, at random times on the 1TB card.  Usually when navigating folders but it has happened during copy/move or rename actions.

When I plug my 400gb card back in with the same exact content, I do not experience crashing issues.

Sorry I can't provide more info.

AMS 0.14.4
FW 10.1.0

**Comment by Galel** [comment]
Same crash here, 1Tb card FAT32 with 64k allocation size. Crashing at navigating to a folder with many files.

**Comment by haywire27** [comment]
@Galel 
Have you tried updating AMS?  I just upgraded to AMS 0.17.1 and this seems to have corrected the issue.
