### ISSUE TITLE
Will there be support for managing files on usb drives in the future?

### ISSUE THREAD

**Issue by zerofo** [joel16/NX-Shell#97]
copy,delete,rename on usb driver.
include file copying cross device.
(like a Portable storage device copy into switch without PC. not install something).

**Comment by joel16** [comment]
It has been planned out for a while now. I just haven't had the time or motivation to sit down and start working on it. The next update may not include anything USB as there are a bunch of other things that's coming (auto update, multi-language support, other fixes etc)

**Comment by joel16** [comment]
v4.00 Added support for USB.
